---
- name: work
  hosts: localhost
  become: true
  vars:
    node_major: "18"

  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: 'dist'

    - name: Install required packages
      apt:
        pkg:
          - software-properties-common
          - build-essential
          - openssh-client
          - ca-certificates
          - ripgrep
          - curl
          - gnupg
          - libncurses-dev

    - name: Clone Vim from repository
      git:
        repo: https://github.com/vim/vim.git
        dest: "~/.local/vim"

    - name: Build Vim from source
      shell: |
        cd ~/.local/vim
        make
        cd ~/.local/vim/src
        make install

    - name: Set up Vim-plug for Vim
      shell: |
        curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

    - name: Add NodeSource repository key
      shell: |
        mkdir -p /etc/apt/keyrings
        curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
        echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_{{ node_major }}.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list
        apt-get update
        apt-get install nodejs -y

    - name: remove bashrc
      shell: rm ~/.bashrc

    - name: symlink vimrc
      file:
        src: "~/.config/gitDotfiles/vim/vimrc"
        dest: "~/.vimrc"
        state: "link"

    - name: symlink .vim/after
      file:
        src: "~/.config/gitDotfiles/vim/after"
        dest: "~/.vim/after"
        state: "link"

    - name: symlink .vim/coc-settings
      file:
        src: "~/.config/gitDotfiles/vim/coc-settings.json"
        dest: "~/.vim/coc-settings.json"
        state: "link"

    - name: symlink .bashrc
      file:
        src: "~/.config/gitDotfiles/bashrc"
        dest: "~/.bashrc"
        state: "link"
