-- local builtin = require('telescope.builtin')
-- vim.keymap.set('n', '<leader>f', builtin.find_files, {})
-- vim.keymap.set('n', '<leader>g', builtin.live_grep, {})
-- vim.keymap.set('n', '<leader>b', builtin.buffers, {})
--
-- local actions = require("telescope.actions")
-- local trouble = require("trouble.providers.telescope")
--
-- require("telescope").setup({
--   defaults = {
--     mappings = {
--       i = { ["<c-t>"] = trouble.open_with_trouble },
--       n = { ["<c-t>"] = trouble.open_with_trouble },
--     },
--     layout_config = {
--       horizontal = {
--         prompt_position = 'bottom',
--       }
--     },
--     path_display = 'truncate'
--   },
--   pickers = {
--     find_files = {
--     }
--   },
--   extensions = {
--     fzf = {
--       fuzzy = true,
--       override_generic_sorter = true,
--       override_file_sorter = true,
--       case_mode = "smart_case"
--     }
--   }
-- })
--
-- require('telescope').load_extension('fzf')
