--KEYMAPS
local keymap = vim.keymap.set
 keymap("i", "jk", "<esc>")
 keymap("n", "<leader>w",":set wrap!<cr>")
 keymap("n", "<leader>p",":set paste!<cr>")
 keymap("n", "<c-]>","<c-]>zz")
 keymap("n", "<c-t>","<c-t>zz")
 keymap("n", "<leader>s",":silent Explore<cr>")
 keymap("n", "<leader>b",":b ")
 keymap("n", ",b",":ls<cr>:b ")
 keymap("n", "<leader>f",":find ")
 keymap("n", "<leader>g",":grep ")
 keymap("n", "<leader>z",":e $MYVIMRC<cr>")
 keymap("n", "<leader>Z",":so $MYVIMRC<cr>")
 keymap("n", "<c-k>",":cp<CR>")
 keymap("n", "<c-j>",":cn<CR>")
 keymap("n", "[a",":prev<cr>")
 keymap("n", "]a",":n<cr>")
 keymap("n", "[A",":first<cr>")
 keymap("n", "]A",":last<cr>")
 keymap("n", "]b",":bnext<cr>")
 keymap("n", "[b",":bprevious<cr>")
 keymap("n", "<bs>","<c-^>")
 keymap("n", "<c-p>",":lprevious<CR>")
 keymap("n", "<c-n>",":lnext<CR>")
 keymap("n", "<leader>c",":cw<cr>")
 keymap("n", "'","`")
 keymap("n", "<leader>/",":g//#<left><left>")
 keymap("v", "J",":m '>+1<cr>gv=gv")
 keymap("v", "K",":m '<-2<cr>gv=gv")
